#####################################
#                                   #
#  Makefile for SCImunito
#  Generated by Bloodshed Dev-C++   #
#                                   #
#####################################


# Compiler
CC=g++
# Parameters given to the compiler
CFLAGS=-s -mwindows -D__DEVC -IC:\PROGRA~1\DEV-C_~1\Include\ -IC:\PROGRA~1\DEV-C_~1\Include\G__~1 -IC:\PROGRA~1\DEV-C_~1\Include\ -LC:\PROGRA~1\DEV-C_~1\Lib\ -BC:\PROGRA~1\DEV-C_~1\Bin\  
# Output filename (*.exe)
OUTPUT="SCImunito.exe"

# Source files
SRCS="C:\Documents and Settings\Enrico\Documenti\Immagina Project\Immagina\Immagina.cpp" "C:\Documents and Settings\Enrico\Documenti\Immagina Project\Immagina\list.cpp" "C:\Documents and Settings\Enrico\Documenti\Immagina Project\Immagina\p56files.cpp" "C:\Documents and Settings\Enrico\Documenti\Immagina Project\Immagina\palette.cpp" "C:\Documents and Settings\Enrico\Documenti\Immagina Project\Immagina\scicell.cpp" "C:\Documents and Settings\Enrico\Documenti\Immagina Project\Immagina\sciloop.cpp" "C:\Documents and Settings\Enrico\Documenti\Immagina Project\Immagina\stdafx.cpp" "C:\Documents and Settings\Enrico\Documenti\Immagina Project\Immagina\v56files.cpp" 
# Output object files (*.o)
OBJS="C:\Documents and Settings\Enrico\Documenti\Immagina Project\Immagina\Immagina.o" "C:\Documents and Settings\Enrico\Documenti\Immagina Project\Immagina\list.o" "C:\Documents and Settings\Enrico\Documenti\Immagina Project\Immagina\p56files.o" "C:\Documents and Settings\Enrico\Documenti\Immagina Project\Immagina\palette.o" "C:\Documents and Settings\Enrico\Documenti\Immagina Project\Immagina\scicell.o" "C:\Documents and Settings\Enrico\Documenti\Immagina Project\Immagina\sciloop.o" "C:\Documents and Settings\Enrico\Documenti\Immagina Project\Immagina\stdafx.o" "C:\Documents and Settings\Enrico\Documenti\Immagina Project\Immagina\v56files.o"  "C:\Documents and Settings\Enrico\Documenti\Immagina Project\Immagina\rsrc.o"

# Standard targets

all: compile_res
	$(CC) -c $(SRCS) $(CFLAGS)
	$(CC) -o $(OUTPUT) $(OBJS) $(CFLAGS)

compile_res:
	windres --include-dir C:\PROGRA~1\DEV-C_~1\Include\ --include-dir C:\PROGRA~1\DEV-C_~1\Include\G__~1 --include-dir C:\PROGRA~1\DEV-C_~1\Include\ --use-temp-file -I rc -O coff -i "C:\DOCUME~1\Enrico\DOCUME~1\IMMAGI~1\Immagina\Immagina.rc" -o "C:\DOCUME~1\Enrico\DOCUME~1\IMMAGI~1\Immagina\Immagina.o"

test: all
	./$(OUTPUT)

clean:
	del *.o

mrproper: clean

