//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Immagina.rc
//
#define ID_NOERROR                      0
#define IDC_MYICON                      2
#define IDD_IMMAGINA_DIALOG             102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDM_MANUAL                      106
#define IDI_IMMAGINA                    107
#define IDC_IMMAGINA                    109
#define IDC_IMMAGINA_ENG                110
#define IDC_LOOP_MIRROR                 110
#define IDD_ABOUTBOX_ENG                113
#define IDR_MAINFRAME                   128
#define IDI_ICON1                       135
#define IDI_SMALL                       135
#define IDD_PROPERTIES_V                136
#define IDD_IMPORT_IMAGE                138
#define IDD_LINKPOINTS                  139
#define IDD_PROPERTIES_P                140
#define IDC_SPIN1                       1000
#define IDC_SPIN2                       1002
#define IDC_RESX                        1003
#define IDC_RESY                        1004
#define IDC_CHECK1                      1005
#define IDC_CHECK2                      1006
#define IDC_LOOP_BASE                   1008
#define IDC_LOOP_CONTINUE               1009
#define IDC_LOOP_STARTCELL              1013
#define IDC_LOOP_ENDCELL                1014
#define IDC_LOOP_REPEAT                 1015
#define IDC_LOOP_STEPSIZE               1016
#define IDC_LINK_COUNT                  1018
#define IDC_CELLS_DELTA                 1019
#define IDC_LOOPS_DELTA                 1020
#define IDC_EDIT1                       1021
#define IDC_POS_PRI                     1021
#define IDC_IMPORT_CLIMIT               1021
#define IDC_IMPORT_TOLERANCE            1023
#define IDC_LINK_TYPE                   1024
#define IDC_SLIDER1                     1028
#define IDC_RESOLUTION                  1029
#define IDC_CELL_PROPERTIES             1030
#define IDC_LINK_X_1                    1050
#define IDC_LINK_X_2                    1051
#define IDC_LINK_X_3                    1052
#define IDC_LINK_X_4                    1053
#define IDC_LINK_X_5                    1054
#define IDC_LINK_X_6                    1055
#define IDC_LINK_X_7                    1056
#define IDC_LINK_X_8                    1057
#define IDC_LINK_X_9                    1058
#define IDC_LINK_X_10                   1059
#define IDC_LINK_X_11                   1060
#define IDC_LINK_Y_1                    1061
#define IDC_LINK_Y_2                    1062
#define IDC_LINK_Y_3                    1063
#define IDC_LINK_Y_4                    1064
#define IDC_LINK_Y_5                    1065
#define IDC_LINK_Y_6                    1066
#define IDC_LINK_Y_7                    1067
#define IDC_LINK_Y_8                    1068
#define IDC_LINK_Y_9                    1069
#define IDC_LINK_Y_10                   1070
#define IDC_LINK_Y_11                   1071
#define IDC_LINK_PRI_1                  1072
#define IDC_LINK_PRI_2                  1073
#define IDC_LINK_PRI_3                  1074
#define IDC_LINK_PRI_4                  1075
#define IDC_LINK_PRI_5                  1076
#define IDC_LINK_PRI_6                  1077
#define IDC_LINK_PRI_7                  1078
#define IDC_LINK_PRI_8                  1079
#define IDC_LINK_PRI_9                  1080
#define IDC_LINK_PRI_10                 1081
#define IDC_LINK_PRI_11                 1082
#define IDC_LINK_TYPE_1                 1083
#define IDC_LINK_TYPE_2                 1084
#define IDC_LINK_TYPE_3                 1085
#define IDC_LINK_TYPE_4                 1086
#define IDC_LINK_TYPE_5                 1087
#define IDC_LINK_TYPE_6                 1088
#define IDC_LINK_TYPE_7                 1089
#define IDC_LINK_TYPE_8                 1090
#define IDC_LINK_TYPE_9                 1091
#define IDC_LINK_TYPE_10                1092
#define IDC_LINK_TYPE_11                1093
#define IDDI_LEFT                       7230
#define IDDI_TOP                        7231
#define IDDI_RESX                       7234
#define IDDI_RESY                       7235
#define ID_IMMAGINE_ESPORTA             32775
#define ID_IMPORTABMP                   32782
#define ID_ESPORTABMP                   32783
#define ID_INFO                         32784

#define ID_CELLASUCCESSIVA              32786
#define ID_CELLAPRECEDENTE              32787
#define ID_CICLOPRECEDENTE              32788
#define ID_CICLOSUCCESSIVO              32789
#define ID_CARICA                       32790
#define ID_SALVA                        32791
#define ID_SALVACOME                    32792
#define ID_CARICAV56VOL                 32793
#define ID_CARICAP56VOL                 32794
#define ID_IMMAGINE_INGRANDIMENTO       32801
#define ID_INGRANDIMENTO_NORMALE        32802
#define ID_INGRANDIMENTO_X2             32803
#define ID_INGRANDIMENTO_X3             32804
#define ID_INGRANDIMENTO_X4             32805
#define ID_PALETTE                      32816
#define ID_COLORI_IMPORTACOLORI         32818
#define ID_COLORI_ESPORTACOLORI         32819
#define ID_PRIORITYBARS                 32824
#define ID_FILE_NEXTFILE                32825
#define ID_Menu                         32829
#define IDM_MODIFY_MENU                 32830
#define IDM_PROPERTIES                  32831
#define IDM_MODIFY                      32832
#define IDM_MODIFY_BOX                  32833
#define ID_IMAGE_LINKPOINTS             32834
#define IDM_LINKPOINTS                  32835
#define ID_LINKS                        -200
#define ID_NOPALETTE                    -121
#define ID_WRONGPALETTELOC              -120
#define ID_WRONGCELLRECSIZE             -110
#define ID_WRONGLOOPRECSIZE             -105
#define ID_WRONGHEADER                  -100
#define IDC_STATIC                      -1
#define ID_CANTOPENFILE                 -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32836
#define _APS_NEXT_CONTROL_VALUE         1031
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
